name: search
version: 0.2.0
description: A 'package:database' middleware that provides a tiny search engine that'
homepage: https://github.com/dint-dev/database

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  charcode: ^1.1.0
  database: ^0.2.2
  meta: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.8.0

dependency_overrides:
  database:
    path: '../database'