name: database_adapter_elasticsearch
version: 0.1.0
description: Adapter between 'package:database' and ElasticSearch.
homepage: https://github.com/dint-dev/database

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  built_value: '>=5.0.0 <8.0.0'
  collection: ^1.14.0
  database: ^0.2.4
  fixnum: ^0.10.0
  meta: ^1.1.0
  universal_io: ^0.8.5

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.8.0

dependency_overrides:
  database:
    path: '../../database'