name: database_adapter_elasticsearch
version: 0.2.2
description:
  Adapter between 'package:database' and Elasticsearch, a full-featured text search engine based on
  Apache Lucene.
homepage: https://github.com/dint-dev/database

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  built_value: ^8.4.3
  collection: ^1.17.1
  database: ^0.3.2
  meta: ^1.9.0
  universal_io: ^2.2.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.23.1

dependency_overrides:
  database:
    path: '../../database'