name: database
version: 0.2.2
description:
  A vendor-agnostic database API. Various adapters are available, such as in-memory database,
  browser APIs, ElasticSearch, and others.
homepage: https://github.com/dint-dev/database

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  built_collection: ^4.0.0
  built_value: '>=5.0.0 <8.0.0'
  charcode: ^1.1.0
  collection: ^1.14.0
  fixnum: ^0.10.0
  meta: ^1.1.0
  protobuf: '>=0.13.0 <2.0.0'
  universal_html: ^1.1.0
  universal_io: ^0.8.5

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.8.0