name: sql_database
version: 0.0.1
description: An adapter for using 'package:database' with SQL databases.
homepage: https://github.com/dint-dev/database

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  database: ^0.2.2
  fixnum: ^0.10.0
  postgres: any

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.8.0

dependency_overrides:
  database:
    path: '../database'