name: datastore
version: 0.1.2
description:
  Enables developers to use document databases and information retrieval systems. Various adapters
  are available in this and other packages.
homepage: https://github.com/terrier989/datastore

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  charcode: ^1.1.0
  collection: ^1.14.0
  firebase: ^7.1.0
  fixnum: ^0.10.0
  googleapis: '>=0.50.0 <0.55.0'
  googleapis_auth: ^0.2.0
  grpc: ^2.0.0
  http: ^0.12.0
  meta: ^1.1.0
  protobuf: '>=0.13.0 <2.0.0'
  test_io: ^0.1.0
  universal_io: ^0.8.5
  universal_html: ^1.1.12

dev_dependencies:
  http2: ^1.0.0
  pedantic: ^1.9.0
  test: ^1.8.0