name: database_adapter_algolia
version: 0.3.0-dev
publish_to: none
description: An adapter for connecting 'package:database' to Algolia. Works in all platforms.
homepage: https://github.com/dint-dev/database

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  database: ^0.3.2
  meta: ^1.9.0
  universal_io: ^2.2.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.23.1
  test_io: ^0.1.2


dependency_overrides:
  database:
    path: '../../database'