name: search
version: 0.2.0
description:
  A simple search engine that enables natural öanguage searches in Flutter / web applications.
homepage: https://github.com/terrier989/datastore

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  charcode: ^1.1.0
  datastore: ^0.1.0
  meta: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.8.0

# dependency_overrides:
#   datastore:
#    path: '../datastore'g